# Generated by Django 6.1 on 2026-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Chicken', 'Chicken'), ('Chinese', 'Chinese'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], default='Burger', max_length=50),
        ),
    ]
